### ISSUE TITLE
viomi.vacuum.v8 (Mi Robot Vacuum Mop Pro) semiautomatic automap problem

### ISSUE THREAD

**Issue by tozwierz** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#221]
Hi.
Thanks to recent corrections and changes I can connect my vacuum cleaner to my homebridge.
Thank you!

Unfortunately, I have a problem downloading the list of rooms from the vacuum cleaner.
I divided the map into rooms in the application as in the Readme.
I have added a room table to the automap property in JSON.
I added scheduled cleanup at 00:00 with selected rooms. It's inactive.
I restarted the homebridge and unfortunately I get the error:

`[5/28/2020, 17:05:03] [Mi Robot Vacuum-Mop P] ERR getRoomList | Failed getting the Room List. Error: Call to device timed out
    at Timeout.retry [as _onTimeout] (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/miio/lib/network.js:519:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7) {
  code: 'timeout'
}
[5/28/2020, 17:05:03] [Mi Robot Vacuum-Mop P] ERR connect | miio.device, next try in 2 minutes | Error: Call to device timed out`

Any hint, please?

**Comment by afharo** [comment]
Can you run homebridge with the environment variable `DEBUG=thing:*`, please? That should provide us with some information about what command is run at the moment of the failure.

**Comment by tozwierz** [comment]
Sure thing.
With `DEBUG=thing:*` I've got:

```
2020-05-28T16:27:23.037Z thing:miio:309266082 -> (5) {"method":"get_timer","params":[],"id":3}
2020-05-28T16:27:25.038Z thing:miio:309266082 -> (4) {"method":"get_timer","params":[],"id":103}
2020-05-28T16:27:27.040Z thing:miio:309266082 -> (3) {"method":"get_timer","params":[],"id":203}
2020-05-28T16:27:29.041Z thing:miio:309266082 -> (2) {"method":"get_timer","params":[],"id":303}
2020-05-28T16:27:31.043Z thing:miio:309266082 -> (1) {"method":"get_timer","params":[],"id":403}
2020-05-28T16:27:33.045Z thing:miio:309266082 -> (0) {"method":"get_timer","params":[],"id":503}
2020-05-28T16:27:35.045Z thing:miio:309266082 Reached maximum number of retries, giving up
[5/28/2020, 18:27:35] [Mi Robot Vacuum-Mop P] ERR getRoomList | Failed getting the Room List. Error: Call to device timed out
    at Timeout.retry [as _onTimeout] (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/miio/lib/network.js:519:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7) {
  code: 'timeout'
}
[5/28/2020, 18:27:35] [Mi Robot Vacuum-Mop P] ERR connect | miio.device, next try in 2 minutes | Error: Call to device timed out
```

**Comment by afharo** [comment]
ok! So it looks like the `get_timer` command is not accepted by that robot... I'll need to find out which one it is... If you happen to find it somehow, I'd appreciate it :)

**Comment by tozwierz** [comment]
I hope we will find it.

**Comment by tozwierz** [comment]
As far as I found I have to discover room ids by hand (https://github.com/rytilahti/python-miio/issues/597 ) 😞

**Comment by afharo** [comment]
Hi! I think [v0.28.0](https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/releases/tag/v0.28.0) should fix this issue. I don't have that model. Would you mind testing it out?

**Comment by kdurek** [comment]
@afharo 
Hi, accidentaly found this thread because it was not working for me
Suddenly I am on v0.28.0 and it's still have problems with autoroom, function that I wished the most :(

**Comment by afharo** [comment]
@kdurek, what is the issue you are facing? Mind sharing the logs?

**Comment by kdurek** [comment]
Sadly my vacoom got broken and gone to warranty. Thanks for asking

**Comment by afharo** [comment]
Oh! I'm sorry! Let me know when you get it back and we can test it out 😇

**Comment by charlesvestal** [comment]
I've got the same vacuum, and see the same issue on the latest plugin version v0.31.1. Happy to test whatever's useful!

[7/11/2024, 8:52:50 AM] [Xiaomi Mi Robot Vaccum 1st Generation] [Model=viomi.vacuum.v8] getFirmware | FirmwareVersion is 3.5.8_0021
[7/11/2024, 8:53:00 AM] [Xiaomi Mi Robot Vaccum 1st Generation] [Model=viomi.vacuum.v8] ERR getRoomMap | Failed getting the Room Map. Error: Call to device timed out
    at DeviceInfo._retryOnTimeout (/homebridge/node_modules/homebridge-xiaomi-roborock-vacuum/src/miio/lib/device_info.js:295:29)
    at DeviceInfo.call (/homebridge/node_modules/homebridge-xiaomi-roborock-vacuum/src/miio/lib/device_info.js:227:12)
    at RoomsService.getRoomMap (/homebridge/node_modules/homebridge-xiaomi-roborock-vacuum/src/services/rooms_service.ts:199:19)
    at RoomsService.init (/homebridge/node_modules/homebridge-xiaomi-roborock-vacuum/src/services/rooms_service.ts:70:9) {
  code: 'timeout'
}
[7/11/2024, 8:53:00 AM] Error: Call to device timed out
    at DeviceInfo._retryOnTimeout (/homebridge/node_modules/homebridge-xiaomi-roborock-vacuum/src/miio/lib/device_info.js:295:29)
    at DeviceInfo.call (/homebridge/node_modules/homebridge-xiaomi-roborock-vacuum/src/miio/lib/device_info.js:227:12)
    at RoomsService.getRoomMap (/homebridge/node_modules/homebridge-xiaomi-roborock-vacuum/src/services/rooms_service.ts:199:19)
    at RoomsService.init (/homebridge/node_modules/homebridge-xiaomi-roborock-vacuum/src/services/rooms_service.ts:70:9)
[7/11/2024, 8:53:00 AM] Got SIGTERM, shutting down Homebridge...

**Comment by afharo** [comment]
@charlesvestal, would you mind running homebridge with the environment variable `DEBUG=thing:*`, please? That should provide us with some information about what command is run at the moment of the failure.
